apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-app-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-app-2
---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: client-app-3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhtas-readers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhtas-reader
subjects:
  - kind: ServiceAccount
    name: client-app-1
    namespace: default
  - kind: ServiceAccount
    name: client-app-2
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhtas-writers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhtas-writer
subjects:
  - kind: ServiceAccount
    name: client-app-1
    namespace: default
