apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhtas-reader
rules:
  - nonResourceURLs: ["/*"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhtas-writer
rules:
  - nonResourceURLs: ["/*"]
    verbs: ["post"]
