apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhtas-network-policy

resources:
- namespace.yaml
- ../shared/cosign
- ../shared/securesign
- policies/

patches:
  - path: patch.yaml