kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: fulcio
spec:
  subdomain: fulcio
  path: /
  to:
    kind: Service
    name: fulcio-server
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
