kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: rekor
spec:
  subdomain: rekor
  path: /
  to:
    kind: Service
    name: rekor-server
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
