kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: search-ui
spec:
  subdomain: search
  path: /
  to:
    kind: Service
    name: rekor-search-ui
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
