kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tuf
spec:
  subdomain: tuf
  path: /
  to:
    kind: Service
    name: tuf
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
