---
- name: Prepare Dex IDP
  hosts: rhtas
  gather_facts: false
  become: yes
  vars:
  vars_files:
    - vars/vars.yml

  tasks:

    - name: Install dnf versionlock plugin
      ansible.builtin.package:
        name: "python3-dnf-plugin-versionlock"
        state: latest

    # Ensure we use the base RHEL 9.4 podman version.
    - name: Lock podman to version 4.9
      ansible.builtin.command:
        cmd: "dnf versionlock add 'podman-4:4.9.4-16.el9_4.x86_64'"

    - name: Configure Dex OIDC instance
      ansible.builtin.include_tasks: dex-setup.yaml
