apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: fulcio-gateway
  namespace: rhtas-gateway-api
  labels:
    kuadrant.io/gateway: "true"
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fulcio
  namespace: rhtas-gateway-api
spec:
  parentRefs:
    - name: fulcio-gateway
  rules:
    - matches:
      - method: GET
        path:
          type: Exact
          value: /api/v1/rootCert
      - path:
          type: PathPrefix
          value: /api/v2
      backendRefs:
        - name: fulcio-server
          port: 80
    - matches:
        - path:
            type: Exact
            value: /api/v1/signingCert
          method: POST
      backendRefs:
        - name: fulcio-server
          port: 80
