apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: build-bot-role
  namespace: test
rules:
  # Allow basic operations on BuildConfigs, builds, and the instantiatebinary subresource.
  - apiGroups: ["build.openshift.io"]
    resources: ["buildconfigs", "buildconfigs/instantiatebinary", "builds"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
    # Allow access to pods and secrets if needed during the build process.
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-bot-rolebinding
  namespace: test
subjects:
  - kind: ServiceAccount
    name: build-bot
    namespace: test
roleRef:
  kind: Role
  name: build-bot-role
  apiGroup: rbac.authorization.k8s.io
