apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhtas-simple

resources:
- namespace.yaml
- ../shared/cosign
- ../shared/securesign

labels:
- includeSelectors: true
  pairs:
    environment: testing

patches:
  - path: patch.yaml