apiVersion: v1
items:
- apiVersion: hive.openshift.io/v1
  kind: ClusterPool
  metadata:
    name: aws-sno
    namespace: rhtas
  spec:
    baseDomain: rhtas.ccitredhat.com
    imageSetRef:
      name: aws-sno-imageset
    platform:
      aws:
        region: us-east-1
        credentialsSecretRef:
          name: aws-creds
    installConfigSecretTemplateRef:
      name: aws-sno-install-config
    size: 1
    skipMachinePools: true
- apiVersion: v1
  kind: Secret
  stringData:
    install-config.yaml: |
      apiVersion: v1
      baseDomain: rhtas.ccitredhat.com
      compute:
      - name: worker
        platform:
          aws:
            type: m5.2xlarge
        replicas: 0
      controlPlane:
        name: master
        platform:
          aws:
            type: m5.xlarge
        replicas: 1
      metadata:
        name: aws-sno
      networking:
        clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        machineNetwork:
        - cidr: 10.0.0.0/16
        networkType: OVNKubernetes
        serviceNetwork:
        - 172.30.0.0/16
      platform:
        aws:
          region: us-east-1
          propagateUserTags: true
      pullSecret: ""
      sshKey: "CHANGEME"
  metadata:
    name: aws-sno-install-config
    namespace: rhtas
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    name: aws-creds
    namespace: rhtas
  stringData:
    aws_access_key_id: CHANGEME
    aws_secret_access_key: CHANGEME
  type: Opaque
- apiVersion: hive.openshift.io/v1
  kind: ClusterImageSet
  metadata:
    name: aws-sno-imageset
    namespace: rhtas
  spec:
    releaseImage: quay.io/openshift-release-dev/ocp-release:4.15.25-x86_64
kind: List
metadata: {}
