apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

namespace: rhtas-mariadb

configMapGenerator:
  - name: initdb-scripts
    options:
      disableNameSuffixHash: true
    behavior: create
    files:
      - initdb.sql=dbconfig.sql

helmCharts:
  - name: mariadb
    releaseName: mariadb
    repo: https://charts.bitnami.com/bitnami
    version: 20.4.1
    valuesFile: values.yaml