apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhtas-mariadb

resources:
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - deployment.yaml

configMapGenerator:
  - name: init-scripts
    options:
      disableNameSuffixHash: true
    files:
      - initdb.sql=dbconfig.sql
      - init-db.sh
